name: Cargo

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
  integration_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore build artifacts
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
    - name: Run integration tests
      run: cargo test --verbose --release --test mod -- --test-threads 1
