name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - run: cargo test --verbose --release --test integration_tests
  test_install_script:
    name: Test install script
    runs-on: ubuntu-latest
    steps:
      - name: Run install script
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/EduardoRodriguesF/quartz/master/install.sh)"
      - name: Quartz path is found
        run: which quartz
      - name: Manpage works
        run: man quartz > /dev/null 2>&1
