name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - run: cargo test --verbose --release --test mod -- --test-threads 1
